### ISSUE TITLE
libcurl configure

### ISSUE THREAD

**Issue by pnorman** [MapQuest/avecado#64]
Running

```
./configure --prefix=$HOME/avecado --with-boost=$HOME/boost \
--with-mapnik-config=$HOME/mapnik/bin/mapnik-config
```

I get the error
```
configure: error: Package requirements (libcurl >= 7.30) were not met:

No package 'libcurl' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LIBCURL_CFLAGS
and LIBCURL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

pkg-config wasn't picking up libcurl, so I tried ``LIBCURL_LIBS="-L/usr/lib/x86_64-linux-gnu -lcurl"`` and``LIBCURL_CFLAGS=`curl-config --cflags` LIBCURL_LIBS=`curl-config --libs```, neither worked.

**Comment by zerebubuth** [comment]
Strange. Is this on Linux (Ubuntu X.Y?) or FreeBSD? Is there a `libcurl.pc` in `$PKG_CONFIG_PATH`?

Also, I don't understand why using the environment variables wouldn't work... That really should be all that's necessary. Autoconf scripts seem to be full of these little corner cases. Could you paste or upload somewhere your `config.log` for that case so that I can see what it's doing wrong, please?

**Comment by pnorman** [comment]
config.log showed it was picking up  pkg-config from the chef install.
